### My loans

GET https://{{host}}/my/loans
Authorization: Bearer {{token}}

### Undocumented: all loans

GET https://{{host}}/game/loans
Authorization: Bearer {{token}}

### Available loans

GET https://{{host}}/types/loans
Authorization: Bearer {{token}}

### Take a loan

POST https://{{host}}/my/loans
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "STARTUP"
}
